// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA42ogD7Z_oNB23_mvxiXJeylmOvSTapQ',
    appId: '1:267687327179:web:8d328779e69ed4da73324e',
    messagingSenderId: '267687327179',
    projectId: 'flutter-app-distribution-792f8',
    authDomain: 'flutter-app-distribution-792f8.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-792f8.firebasestorage.app',
    measurementId: 'G-E6XFZPFNJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhfxYikacOJm3Guq5v_Uh5qbY2heZENPA',
    appId: '1:267687327179:android:a9674e95d38a248e73324e',
    messagingSenderId: '267687327179',
    projectId: 'flutter-app-distribution-792f8',
    storageBucket: 'flutter-app-distribution-792f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS6sHwkWUVDk-WTPqrJRRiGdV9FOAJdWM',
    appId: '1:267687327179:ios:e9a0ab97e66a75ec73324e',
    messagingSenderId: '267687327179',
    projectId: 'flutter-app-distribution-792f8',
    storageBucket: 'flutter-app-distribution-792f8.firebasestorage.app',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS6sHwkWUVDk-WTPqrJRRiGdV9FOAJdWM',
    appId: '1:267687327179:ios:e9a0ab97e66a75ec73324e',
    messagingSenderId: '267687327179',
    projectId: 'flutter-app-distribution-792f8',
    storageBucket: 'flutter-app-distribution-792f8.firebasestorage.app',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA42ogD7Z_oNB23_mvxiXJeylmOvSTapQ',
    appId: '1:267687327179:web:f7d3f3fa8b986bc373324e',
    messagingSenderId: '267687327179',
    projectId: 'flutter-app-distribution-792f8',
    authDomain: 'flutter-app-distribution-792f8.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-792f8.firebasestorage.app',
    measurementId: 'G-GS7S4SZZC3',
  );
}
